name: EEGToText
channels:
  - pytorch
  - anaconda
  - conda-forge
  - huggingface
dependencies:
  - pytorch=2.2.0
  - numpy=1.22.1
  - torchaudio=2.2.0
  - cudatoolkit=12.4
  - scipy=1.12.0
  - h5py=3.10.0
  - tqdm=4.66.2
  - matplotlib=3.8.3
  - transformers=4.38.2
  - nltk=3.8.1
  - pip=24.0
  - pip:
    - fuzzy-match==0.0.1
    - rouge==1.0.1

    # Updated Libraries
